apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardsofspite-api
  namespace: cardsofspite
spec:
  selector:
    matchLabels:
      app: cardsofspite-api
  template:
    metadata:
      labels:
        app: cardsofspite-api
    spec:
      containers:
        - name: cardsofspite-api
          image: localhost:6000/cardsofspite-api:1.0.0
          env:
            - name: AZURITE_HOST
              value: cardsofspite-azurite-service
            - name: ApiKeyOptions__ApiKey
              value: 60A5D3E4100FE8AFA5EE0103739A45711D50D7F3BA7280D8A95B51F5D04AA4B8
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: cardsofspite-api-service
  namespace: cardsofspite
spec:
  selector:
    app: cardsofspite-api
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
